spring:
  datasource:
    url:
      jdbc:postgresql://localhost:5432/Emp
    username:
      postgres
    password:
      1697
    driver-class-name:
      org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:
        update
server:
  port:
    8080
